# Generated by Django 4.1.2 on 2022-10-15 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_artiste_age_lyics_song_lyics_content_song_artiste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('Artiste', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.DeleteModel(
            name='Lyics',
        ),
        migrations.AddField(
            model_name='lyrics',
            name='Song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
        ),
    ]
